spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clippy}
    username: ${SPRING_DATASOURCE_USERNAME:clippy}
    password: ${SPRING_DATASOURCE_PASSWORD:clippy}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8080}
